"""message

Revision ID: a4e1d72801d7
Revises: e8dddce68d41
Create Date: 2023-09-01 08:56:44.712665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e1d72801d7'
down_revision = 'e8dddce68d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('age')

    # ### end Alembic commands ###
