"""message

Revision ID: a62a0baa3bca
Revises: cd69a108240b
Create Date: 2023-08-29 15:23:46.603883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a62a0baa3bca'
down_revision = 'cd69a108240b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drinks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredient_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('strIngredient1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('strIngredient2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('strIngredient3', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('strIngredient4', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('strIngredient5', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('strIngredient6', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('strIngredient7', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('strIngredient8', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('strIngredient9', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('strIngredient10', sa.String(), nullable=True))
        batch_op.drop_constraint('fk_drinks_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ingredients_drink_id_drinks', type_='foreignkey')
        batch_op.drop_column('drink_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drink_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_ingredients_drink_id_drinks', 'drinks', ['drink_id'], ['id'])

    with op.batch_alter_table('drinks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_drinks_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('strIngredient10')
        batch_op.drop_column('strIngredient9')
        batch_op.drop_column('strIngredient8')
        batch_op.drop_column('strIngredient7')
        batch_op.drop_column('strIngredient6')
        batch_op.drop_column('strIngredient5')
        batch_op.drop_column('strIngredient4')
        batch_op.drop_column('strIngredient3')
        batch_op.drop_column('strIngredient2')
        batch_op.drop_column('strIngredient1')
        batch_op.drop_column('ingredient_id')

    # ### end Alembic commands ###
