"""message

Revision ID: b56af9c8d229
Revises: 2c0c27c3489a
Create Date: 2023-08-30 12:30:07.518166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b56af9c8d229'
down_revision = '2c0c27c3489a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drink_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_ingredients_drink_id_drinks'), 'drinks', ['drink_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drink_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_drink_id_drinks'), 'drinks', ['drink_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_drink_id_drinks'), type_='foreignkey')
        batch_op.drop_column('drink_id')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ingredients_drink_id_drinks'), type_='foreignkey')
        batch_op.drop_column('drink_id')

    # ### end Alembic commands ###
