"""message

Revision ID: b908c5d4eb12
Revises: 2da401b33ec7
Create Date: 2023-08-30 13:56:24.103428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b908c5d4eb12'
down_revision = '2da401b33ec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_drink_id_drinks', type_='foreignkey')
        batch_op.drop_column('drink_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drink_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_users_drink_id_drinks', 'drinks', ['drink_id'], ['id'])

    # ### end Alembic commands ###
