"""message

Revision ID: c32cb64a5807
Revises: b56af9c8d229
Create Date: 2023-08-30 13:32:29.279807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c32cb64a5807'
down_revision = 'b56af9c8d229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drink_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drink_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drink_id'], ['drinks.id'], name=op.f('fk_drink_ingredients_drink_id_drinks')),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_drink_ingredients_ingredient_id_ingredients')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_drinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('drink_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drink_id'], ['drinks.id'], name=op.f('fk_user_drinks_drink_id_drinks')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_drinks_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('drinassociations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drinassociations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('drink_id', sa.INTEGER(), nullable=True),
    sa.Column('ingredient_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['drink_id'], ['drinks.id'], name='fk_drinassociations_drink_id_drinks'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name='fk_drinassociations_ingredient_id_ingredients'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_drinks')
    op.drop_table('drink_ingredients')
    # ### end Alembic commands ###
