"""message

Revision ID: e8dddce68d41
Revises: b908c5d4eb12
Create Date: 2023-08-30 14:11:41.743550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8dddce68d41'
down_revision = 'b908c5d4eb12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ingredients_drink_id_drinks', type_='foreignkey')
        batch_op.drop_column('drink_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drink_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_ingredients_drink_id_drinks', 'drinks', ['drink_id'], ['id'])

    # ### end Alembic commands ###
